// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wordservice_test

import (
	"context"
	"github.com/avrebarra/basabaso/subsys/wordservice"
	"github.com/avrebarra/basabaso/subsys/wordstore"
	"sync"
)

// Ensure, that StoreMock does implement wordservice.Store.
// If this is not the case, regenerate this file with moq.
var _ wordservice.Store = &StoreMock{}

// StoreMock is a mock implementation of wordservice.Store.
//
//     func TestSomethingThatUsesStore(t *testing.T) {
//
//         // make and configure a mocked wordservice.Store
//         mockedStore := &StoreMock{
//             FindFunc: func(ctx context.Context, in wordstore.FindInput) ([]wordstore.User, int64, error) {
// 	               panic("mock out the Find method")
//             },
//             PersistFunc: func(ctx context.Context, in *wordstore.User) error {
// 	               panic("mock out the Persist method")
//             },
//         }
//
//         // use mockedStore in code that requires wordservice.Store
//         // and then make assertions.
//
//     }
type StoreMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, in wordstore.FindInput) ([]wordstore.Word, int64, error)

	// PersistFunc mocks the Persist method.
	PersistFunc func(ctx context.Context, in *wordstore.Word) error

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In wordstore.FindInput
		}
		// Persist holds details about calls to the Persist method.
		Persist []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *wordstore.Word
		}
	}
	lockFind    sync.RWMutex
	lockPersist sync.RWMutex
}

// Find calls FindFunc.
func (mock *StoreMock) Find(ctx context.Context, in wordstore.FindInput) ([]wordstore.Word, int64, error) {
	callInfo := struct {
		Ctx context.Context
		In  wordstore.FindInput
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	if mock.FindFunc == nil {
		var (
			out   []wordstore.Word
			total int64
			err   error
		)
		return out, total, err
	}
	return mock.FindFunc(ctx, in)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//     len(mockedStore.FindCalls())
func (mock *StoreMock) FindCalls() []struct {
	Ctx context.Context
	In  wordstore.FindInput
} {
	var calls []struct {
		Ctx context.Context
		In  wordstore.FindInput
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// Persist calls PersistFunc.
func (mock *StoreMock) Persist(ctx context.Context, in *wordstore.Word) error {
	callInfo := struct {
		Ctx context.Context
		In  *wordstore.Word
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockPersist.Lock()
	mock.calls.Persist = append(mock.calls.Persist, callInfo)
	mock.lockPersist.Unlock()
	if mock.PersistFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.PersistFunc(ctx, in)
}

// PersistCalls gets all the calls that were made to Persist.
// Check the length with:
//     len(mockedStore.PersistCalls())
func (mock *StoreMock) PersistCalls() []struct {
	Ctx context.Context
	In  *wordstore.Word
} {
	var calls []struct {
		Ctx context.Context
		In  *wordstore.Word
	}
	mock.lockPersist.RLock()
	calls = mock.calls.Persist
	mock.lockPersist.RUnlock()
	return calls
}
